version: '3.8'

volumes:
  jenkins_home:
    name: ${JK_VOLUME_NAME}

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: ${JK_CONTAINER_NAME}
    ports:
      - "${JK_LOCAL_PORT1}:8080"
      - "${JK_LOCAL_PORT2}:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: on-failure
  ssh-agent:
    image: jenkins/ssh-agent
