parameters:
  - name: directory
    type: string 
    default: '$(System.DefaultWorkingDirectory)'

steps:
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
    displayName: 'Terraform : init'
    inputs:
      provider: aws
      command: init
      workingDirectory: '${{ parameters.directory }}'
      backendServiceAWS: 'Iac_builder_terraform'
      backendAWSBucketName: backend-terraform-simple
      backendAWSKey: prod-state
      
  - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV3@3
    displayName: 'Terraform : destroy'
    inputs:
      provider: aws
      command: destroy
      workingDirectory: '${{ parameters.directory }}'
      commandOptions: '-auto-approve'
      environmentServiceNameAWS: 'Iac_builder_terraform'
