AWSTemplateFormatVersion: 2010-09-09

Description: >
  Este stack va a crear una instancia
  y todo lo que necesita

Parameters:
  InstanceTypeParameter:
    Type: String

  InstanceAmiParameter:
    Type: String

Resources:
  SecurityGroupSSH:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Security group para acceso SSH'
      GroupName: 'SSHSecurityGroup'
      VpcId: 'vpc-08f225422c3ed465b'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: 0
          ToPort: 0
          CidrIp: 0.0.0.0/0
  
  keyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: 'WebServerKeyPair'
      KeyType: 'rsa'

  WebServer:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref InstanceAmiParameter
      InstanceType: !Ref InstanceTypeParameter
      KeyName: !Ref keyPair
      SecurityGroupIds: 
        - !Ref SecurityGroupSSH
      UserData: 
        Fn::Base64: |
          #!/bin/bash
          sudo apt update -y
          sudo apt install nginx -y

          cd /var/www
          sudo mkdir tutorial
          cd tutorial
          
          sudo tee -a index.html <<EOF
            <!doctype html>
            <html>
            <head>
              <meta charset="utf-8">
              <title>Hello, Nginx!</title>
            </head>
            <body>
              <h1>Hello, Nginx!</h1>
              <p>We have just configured our Nginx web server on Ubuntu Server!</p>
            </body>
            </html>
          EOF

          cd /etc/nginx/sites-enabled

          sudo tee -a tutorial <<EOF
            server {
              listen 80;
              listen [::]:80;
          
              server_name example.ubuntu.com;
          
              root /var/www/tutorial;
              index index.html;
          
              location / {
                      try_files $uri $uri/ =404;
              }
            }
          EOF

          sudo service nginx restart

Outputs:
  InstanceId:
    Description: 'Id from created instance'
    Value: !Ref WebServer