trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  - name: terraformDirectory
    value: 'Iac/Terraform'
  - name: infraDirectory
    value:  'azure_pipelines_templates/Infrastructure'
  - name: appDirectory
    value: 'azure_pipelines_templates/App'
  - name: envFile
    value: '.env.dev'

stages:
  - stage: Deploy_Infrastructure
    displayName: 'Deploying AWS resources'
    condition: and(always(), contains(variables['build.sourceBranch'], 'refs/heads/main'))
    jobs:
      - job: Install_Check_Terraform
        steps:
          - template: '${{ infraDirectory }}/Install_terraform.yml'

      - job: Deploy_Resources
        dependsOn: Install_Check_Terraform
        condition: succeeded()
        steps:
          - template: '${{ infraDirectory }}/Build_resource.yml'
            parameters:
              directory: '${{ variables.terraformDirectory }}'
      
      - job: Serve_App
        dependsOn: Deploy_Resources
        condition: succeeded()
        steps:
          - template: '${{ appDirectory }}/Install_App.yml'
            parameters:
              directory: '${{ variables.envFile }}'

      - job: waitForValidation
        displayName: 'Wait for external validation'
        pool: server
        timeoutInMinutes: 4320 # job times out in 3 days
        dependsOn: Serve_App
        condition: succeeded()
        steps:
          - task: ManualValidation@0
            timeoutInMinutes: 1440 # task times out in 1 day
            inputs:
              instructions: 'Please validate if you want to destroy the deployed infrastructured'
              onTimeout: 'reject'

      - job: Destroy_Resources
        dependsOn: 
          - waitForValidation
          - Deploy_Resources
          - Serve_App
        condition: |
          or
          (
            eq(dependencies.waitForValidation.result, 'Succeeded'),
            eq(dependencies.Deploy_Resources.result, 'failed'),
            eq(dependencies.Serve_App.result, 'failed')
          )
        steps:
          - template: '${{ infraDirectory }}/Destroy_resource.yml'
            parameters:
              directory: '${{ variables.terraformDirectory }}'
