trigger:
  - main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Deploy_Infrastructure
    displayName: 'Deploying AWS resources'
    condition: and(always(), contains(variables['build.sourceBranch'], 'refs/heads/main'))
    jobs:
      - job: Install_Check_Terraform
        steps:
          - template: 'azure_pipelines_templates/Install_terraform.yml'

      - job: Deploy_Resources
        dependsOn: Install_Check_Terraform
        condition: succeeded()
        steps:
          - template: 'azure_pipelines_templates/Build_resource.yml'
            parameters:
              directory: 'Iac/Terraform'
